# Generated by Django 5.1.4 on 2025-01-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_content_options_alter_lecture_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
